index:
    pattern:  /index/
    defaults: { _controller: UniplacesBabelateBundle:Babelate:index }

show_bundles:
    pattern: /show_bundles/
    defaults: { _controller: UniplacesBabelateBundle:Babelate:showBundles }

show_domains:
    pattern: /show_domains/{bundle}
    defaults: { _controller: UniplacesBabelateBundle:Babelate:showDomains }
   
show_keys:
    pattern: /show_keys/{bundle}/{domain}
    defaults: { _controller: UniplacesBabelateBundle:Babelate:showKeys }

show_key:
    pattern: /show_key/{bundle}/{domain}/{key}
    defaults: { _controller: UniplacesBabelateBundle:Babelate:showKey }

update_key:
    pattern: /update_key/{bundle}/{domain}/{key}
    defaults: { _controller: UniplacesBabelateBundle:Babelate:updateKey }
    requirements:
      _method: POST

show_keys_missing_locale:
    pattern: /show_keys_missing_locale/{bundle}/{domain}/{locale}
    defaults: { _controller: UniplacesBabelateBundle:Babelate:showKeysMissingLocale }
